### ISSUE TITLE
Update for 2.37

### ISSUE THREAD

**Issue by gjf** [elgesl/keepass-mswifiimport#4]
Could you please update the plugin to work with KeePass 2.37?

**Comment by elgesl** [comment]
I hadn't any problem with the old plugin version and KeePass 2.37. Nevertheless, I just uploaded a new version which included a fix for two bugs. However, those were independent of the KeePass version: One could leed to a crash of KeePass, the other one to not being able to reimport wifi information to windows (fixable, see below).

Just for the case that you had the bad luck to be effected by one of those bugs, please update your plugin version. If that does not fix your problem, please see a bug description in [Help: It does not show the In Windows einfügen entry. What can I do?](https://elgesl.github.io/keepass-mswifiimport/exporttowindows.html) whether this fixes your problem.

If this does not, please write me a more specific bug description and I will directly see what I can do.
If one of the above helps, please let me know, so I do not have to worry any more :-)

**Comment by gjf** [comment]
When previous version was installed KeePass 2.37 shows a warning that the plugin is not compatible with current version of KeePass so it won't be loaded.

Now everything works properly, so thank you for update.
